### ISSUE TITLE
Add color legend

### ISSUE THREAD

**Issue by manthey** [XDATA-Year-3/geoapp#102]

**Comment by manthey** [comment]
We could allow selecting this in some manner to alter the colors used, in case the user wants to customize the colors.  I don't know if that is a good idea or not, as then different users could see radically different colors.  We had a user suggest it, though.

**Comment by jeffbaumes** [comment]
While selecting colors would be nice, I'd definitely start with a static legend.

**Comment by manthey** [comment]
The legend could be integrated with selection controls.  For instance:
  `[ ]` (blue dot) Taxi pickups,  `[ ]` (yellow dot) Taxi drop offs.  `[ ]` (blue-to-yellow line) Taxi trip vectors  `[ ]` (red dot) Messages
Doing so would eliminate the Display Type control.  If you selected binning, the show options would have to change to `[ ]` (shaded square) Taxi pickups, etc.

Rather than doing this, a legend just near the Show control would also work.  In this case, the legend would only indicate items that are displayed.

Other's thoughts are welcome.

**Comment by jeffbaumes** [comment]
Either of these approaches could work, but a separate legend near Show or in a separate panel sounds a bit cleaner since only visual markers for what is currently displayed would be visible.

**Comment by manthey** [comment]
Added in PR #132.
