### ISSUE TITLE
Add controls to select opacity.

### ISSUE THREAD

**Issue by manthey** [XDATA-Year-3/geoapp#12]

**Comment by jeffbaumes** [comment]
Possibly use sigmoidal control

**Comment by jeffbaumes** [comment]
Possibly have an "auto adjust" feature

**Comment by manthey** [comment]
I added the maximum number of points option in PR #57, so I've changed this issue to just be the opacity instead of both options.

**Comment by manthey** [comment]
Added in PR #75.
