### ISSUE TITLE
Cancel database queries when appropriate

### ISSUE THREAD

**Issue by manthey** [XDATA-Year-3/geoapp#140]
Currently, if you ask for some data, then ask for more data before the first query completes, the first query will still complete on the database backend.  This means, for instance, that clicking filter many times can load the system.  There is poor support for cancelling postgres queries that are in progress, but it is possible if a client has its own connection.

For a low-number of clients asking questions at once, this should be possible (see, for instance, http://thebesthacker.com/question/cancel-query-execution-in-pyscopg2.html).  Currently, we mostly share a single database connection for all clients (one connection per distinct database).  I think this means that we would have to increase the postgres available connections, or have some intelligent connection pooling (have _n_ connections, where each client gets a distinct connection if available).

**Comment by jamiesnape** [comment]
Loosely related, one user wanted an explicit "cancel" button.

**Comment by manthey** [comment]
Add in PR #191.
