### ISSUE TITLE
UI: Automatically update geospatial bins on pan/zoom of viewport

### ISSUE THREAD

**Issue by zachmullen** [XDATA-Year-3/geoapp#147]
This should at least be an option. It would be fine to do it using a small delay to avoid recomputing too much during interaction.

**Comment by manthey** [comment]
Based on what I observed, I think making this require updating is more confusing than the theoretical benefit it provides.  Therefore, I think it should just auto-update upon map movement.

I'm thinking that the bin number control should also be a slider.  @zachmullen and @jeffbaumes do you think a range from 5 to 30 makes sense?  See parakon:8001 for an example.

**Comment by zachmullen** [comment]
:+1: , that's the functionality I was hoping for, and I do like the slider for number of bins, it makes it easier to explore for first time users (most didn't seem to know what a reasonable value to type into the text field would be).

**Comment by manthey** [comment]
Done in PR #158.
