### ISSUE TITLE
UI: Clicking text of dataset name in dialog should toggle the box

### ISSUE THREAD

**Issue by zachmullen** [XDATA-Year-3/geoapp#149]
Bootstrap will take care of this for us if we put the checkbox inside of the label and add a `checkbox` class to the outer label.

**Comment by manthey** [comment]
Originally, I thought people would drag the datasets around to change the order on the graph or scatter plot, and went with that as the default behavior.  Clearly toggling would have been the better default behavior.

**Comment by zachmullen** [comment]
Would it be tricky to get both? Like, a click toggles the box, but a mousedown+drag still works like it does now?

**Comment by manthey** [comment]
I'll find out.

**Comment by zachmullen** [comment]
By the way, for these minor things, feel free to assign them to me. I imagine I can take care of many of these little UI tweaks without having to know a great deal about the application :)

**Comment by manthey** [comment]
Feel free to work on any of the UI issues if you have the time.
