### ISSUE TITLE
UI: Make button to sync search intervals of taxi data and message data more prominent

### ISSUE THREAD

**Issue by jamiesnape** [XDATA-Year-3/geoapp#160]
So you do not have too set the same data twice.

**Comment by manthey** [comment]
There is a checkbox called "Use pickup date range" which does this.  When checked, the messages use the same date range as the taxi data.

**Comment by manthey** [comment]
I think it would be more obvious if, when checked, we hid the message date field.  Also, I think making it checked by default would be better.

**Comment by jamiesnape** [comment]
Good idea. People always seemed to miss it.

**Comment by jamiesnape** [comment]
Several people suggested just one date interval. No one had a use case for different intervals for messages and taxi data (although they would have liked to see different intervals for the same data together on the map in different colors).

**Comment by manthey** [comment]
I've reduced this to just one date field in PR #169.
