### ISSUE TITLE
Minerva Permits should have a paragraph elevator pitch when first opened

### ISSUE THREAD

**Issue by cpatrick** [XDATA-Year-3/geoapp#221]
This should give some context before thrusting the user into the deep end of geospatial data analysis. The user can then dismiss it and start doing things.

**Comment by jeffbaumes** [comment]
+1 @manthey could you add something like what I have below? We also need the controls to be more self-documenting, and turn a few into drop-down menus.

Overview text:

Minerva Permits lets you explore permit, crime, and code violation data in Boston using data from the [City of Boston](https://data.cityofboston.gov/). Use the controls on the left to display points or a dynamically generated binned heatmap on the data, and to filter down your search to specific types of permits, crimes, or violations. The animation controls let you cycle through the queried data to view weekly or daily patterns.

This application is [open source](https://github.com/XDATA-Year-3/geoapp) and was built with [Kitware's Resonant](http://resonant.kitware.com/) platform, including [Girder](http://girder.readthedocs.org/) for data management and [GeoJS](http://opengeoscience.github.io/geojs/examples/index.html) for scalable visualization.

Large button "Explore"

Or start with one of these preconfigured visualizations:

[Predicting new construction](http://demo.kitware.com/bostonpermits/#mapview?map=x0%3D-71.3325043%26y0%3D42.4180018%26x1%3D-70.8414917%26y1%3D42.2240005%26zoom%3D12.84&graph=series0%3Dinternal.fullrange%26type0%3Dline%26bin0%3Dday%26series1%3Dpermit.layer%252Cpermitsboston.permits_total_est_buildings%26type1%3Dline%26bin1%3Dmonth%26series2%3Dpermit.layer%252Cpermitsboston.permits_total_est_buildings%26type2%3Dscatter%26bin2%3Dmonth&permit-filter=ga-permit-source%3Dbostonpermit%26ga-permit-permittypedescr_search%3DErect%252FNew%2BConstruction%26ga-permit-occupancytype_search%3Dfam%257Cmulti%257Cother%257Cunit%257Cmore%26ga-data-permit%3D1000000&panels=ga-anim-settings%3Dtrue%26ga-violation-settings%3Dfalse%26ga-crime-settings%3Dfalse&general-filter=ga-region%3D&general-display=ga-tile-set%3Dmapbox%26ga-tile-opacity%3D0.65&permit-display=ga-show-permit-data%3Dtrue%26ga-display-permit-process%3Draw%26ga-display-max-permit-points%3D1000000%26ga-display-permit-num-bins%3D15%26ga-permit-opacity%3D0.328&crime-display=ga-show-crime-data%3Dfalse%26ga-display-crime-process%3Draw%26ga-display-max-crime-points%3D25000%26ga-display-crime-num-bins%3D15%26ga-crime-opacity%3D0.1&violation-display=ga-show-violation-data%3Dfalse%26ga-display-violation-process%3Draw%26ga-display-max-violation-points%3D25000%26ga-display-violation-num-bins%3D15%26ga-violation-opacity%3D0.1) - From the raw city data, this view attempts to reconstruct the [U.S. Census new residential construction estimates](http://www.census.gov/construction/nrc/index.html) by restricting the permits displayed on the map. The monthly correlation between the true and reconstructed data can be viewed on the left both as a timeline and scatterplot. Can you verify using the satellite view that these are indeed new residential construction sites? Can you adjust the query parameters to obtain a closer match?

[Correlating demolition with unsafe structures](http://demo.kitware.com/bostonpermits/#mapview?permit-filter=ga-permit-source%3Dbostonpermit%26ga-permit-comments_search%3Ddemolish%257Cdemolition%26ga-data-permit%3D1000000&panels=ga-anim-settings%3Dfalse%26ga-violation-settings%3Dtrue%26ga-crime-settings%3Dfalse&violation-filter=ga-violation-source%3Dbostonviolation%26ga-violation-category_search%3DUnsafe%2Bstructure%26ga-data-violation%3D1000000&general-filter=ga-region%3D&general-display=ga-tile-set%3Dmapbox%26ga-tile-opacity%3D0.65&permit-display=ga-show-permit-data%3Dtrue%26ga-display-permit-process%3Dbinned%26ga-display-max-permit-points%3D1000000%26ga-display-permit-num-bins%3D20%26ga-permit-opacity%3D0.328&crime-display=ga-show-crime-data%3Dfalse%26ga-display-crime-process%3Draw%26ga-display-max-crime-points%3D25000%26ga-display-crime-num-bins%3D15%26ga-crime-opacity%3D0.1&violation-display=ga-show-violation-data%3Dtrue%26ga-display-violation-process%3Dbinned%26ga-display-max-violation-points%3D1000000%26ga-display-violation-num-bins%3D20%26ga-violation-opacity%3D0.1&graph=series0%3Dinternal.fullrange%26type0%3Dline%26bin0%3Dday%26series1%3Dpermit.layer%252Cviolation.layer%26type1%3Dline%26bin1%3Dmonth%26series2%3Dpermit.layer%252Cviolation.layer%26type2%3Dscatter%26bin2%3Dmonth&map=x0%3D-71.1233521%26y0%3D42.3764805%26x1%3D-70.9765320%26y1%3D42.3184923%26zoom%3D14.58) - In this view, red represents demolition permits, and blue represents unsafe structure code violations. A mixture (purple) shows areas where both demolition and unsafe structures are abundant, while strong red or blue designates areas where only demolition or unsafe structures are predominant. What areas are seeing reconstruction of aging buildings (predominantly purple)? What areas are seeing unsafe structures that are not being revitalized (predominately blue)? Can you find any specific locations where a site is cited as an unsafe structure and is later issued a permit for demolition?

**Comment by jeffbaumes** [comment]
One more starting point:

[Residential trash violations](http://demo.kitware.com/bostonpermits/#mapview?permit-filter=ga-permit-source%3Dbostonpermit%26ga-permit-comments_search%3Ddemolish%257Cdemolition%26ga-data-permit%3D1000000&panels=ga-anim-settings%3Dtrue%26ga-violation-settings%3Dtrue%26ga-crime-settings%3Dfalse%26ga-permit-settings%3Dfalse&general-display=ga-tile-set%3Dmapbox%26ga-tile-opacity%3D0.65&permit-display=ga-show-permit-data%3Dfalse%26ga-display-permit-process%3Dbinned%26ga-display-max-permit-points%3D1000000%26ga-display-permit-num-bins%3D20%26ga-permit-opacity%3D0.328&crime-display=ga-show-crime-data%3Dfalse%26ga-display-crime-process%3Draw%26ga-display-max-crime-points%3D25000%26ga-display-crime-num-bins%3D15%26ga-crime-opacity%3D0.1&violation-display=ga-show-violation-data%3Dtrue%26ga-display-violation-process%3Draw%26ga-display-max-violation-points%3D1000000%26ga-display-violation-num-bins%3D20%26ga-violation-opacity%3D0.012&graph=series0%3Dinternal.fullrange%26type0%3Dline%26bin0%3Dday%26series1%3Dviolation.layer%26type1%3Dline%26bin1%3Dmonth&violation-filter=ga-violation-source%3Dbostonviolation%26ga-violation-category_search%3Dtrash%253A%2Bres%26ga-data-violation%3D1000000&general-filter=ga-region%3D&map=x0%3D-71.1745148%26y0%3D42.3915918%26x1%3D-70.9750977%26y1%3D42.3128423%26zoom%3D14.14&anim=ga-cycle%3Dweek%26ga-cycle-group%3Dday%26ga-cycle-duration%3D10-s%26ga-cycle-framerate%3D30%26ga-play%3Dstop) - This view animates the residential code violations for misplacement of trash using a weekly cycle. Wait for the full data to load then press Play to show the animation. Can you determine the likely trash pickup dates for various Boston neighborhoods?

**Comment by manthey** [comment]
Added in PR #224.
