### ISSUE TITLE
Incremental data loading

### ISSUE THREAD

**Issue by jeffbaumes** [XDATA-Year-3/geoapp#23]

**Comment by jeffbaumes** [comment]
Investigate keeping cursor open - streaming.

**Comment by manthey** [comment]
In postgres, the bulk of the time is spent before ANY data is returned by the cursor.  For example, in a request that takes 15 second, the first data is returned around 14.5 seconds after the request is started, and then I can fetch 300,000 records in less than 0.5 seconds (including converting them to a desired format).
