### ISSUE TITLE
What is Update in Display pane for?

### ISSUE THREAD

**Issue by jeffbaumes** [XDATA-Year-3/geoapp#95]
Since updates happen immediately, why do we need an Update button?

**Comment by manthey** [comment]
If you move the map (pan or zoom), it rebins the binned data.

**Comment by jeffbaumes** [comment]
Ah I see. I'd suggest renaming to "Update Bins" and disabling the button if you are not in a heatmap view mode. If there's a use case outside updating bins we could go back on that but seems most clear for now.

**Comment by manthey** [comment]
Refactored in PR #99.

**Comment by jeffbaumes** [comment]
"Update bins" seems to work how I'd expect now - thanks.
